[package]
name = "renderer"
version = "0.1.0"
authors = ["Luke"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
erupt="0.14"
winit="0.21.0"
raw-window-handle = "0.3.3"

[dev-dependencies]
mockall="0.6.0"