[package]
name = "ui"
version = "0.1.0"
authors = ["Luke <galactic.fungus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit="0.23.0"
renderer = { path = "../renderer" }
erupt = "0.15"